Vinscant rust
ZeusWPI/ZeSS pull request #69
Opened 2024-09-11 19:29 UTC by draxaris1010

TODO:
- [ ] buzzer

2025-07-10 21:44 UTC, hanneskt requested changes
Nice! Most of your code seems really good and you show a good understanding of most Rust syntax, but some slight tweaks can be made!

2025-07-10 21:44 UTC, hannes-dev commented on vinscant/src/main.rs
> +        for numerator in [1, 2, 3, 4, 5, 6].iter().cycle() {
```suggestion
        for numerator in (1..=6).cycle() {
```
use the range syntax

2025-07-10 21:44 UTC, hannes-dev commented on vinscant/src/main.rs
> +            timer_driver.set_frequency(Into::<Hertz>::into(numerator * 100));
can you just do `(numerator * 100).into()` or does that not work?

2025-07-10 21:44 UTC, hannes-dev commented on vinscant/src/main.rs
> +                last_uid = uid.as_bytes().encode_hex();
any reason you mix `hex::encode()` and `.encode_hex()`?

additionally, it seems like you could just compare the bytes instead of converting to hex every time, and only convert when talking with the server.

2025-07-10 21:44 UTC, hannes-dev commented on vinscant/src/ping_pong.rs
> +        }
Maybe think about this again to make this more readable, I believe in you :)

2025-07-25 23:04 UTC, hannes-dev commented on vinscant/README.md
> +  - Or switch to Linux (recommended option)
😆

2025-07-25 23:05 UTC, hannes-dev commented on vinscant/src/wifi.rs
> +    }
does this now actually fix the issue?

2025-08-21 22:29 UTC, hannes-dev approved these changes
Looks really nice overall :)

2025-08-22 19:22 UTC, merged